server:
  port: 8086
spring:
  application:
    name: zuul-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8798/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    instance_id: ${spring.cloud.client.hostname}:${server.port}:${spring.application.name}:@project.version@
hystrix:
  command:
    default:
      execution:
        timeout:
          enbale: true
        isolation:
          thread:
            timeoutInMilliseconds: 1000
